#!/usr/bin/env python3
import os
import argparse
import yaml
from jinja2 import Environment, FileSystemLoader

parser = argparse.ArgumentParser(description='Generates cv from json cv data')
parser.add_argument('yaml')
parser.add_argument('template')
parser.add_argument('output')
args = parser.parse_args()

tmpl_dir = os.path.dirname(os.path.abspath(args.template))
environment = Environment(
    loader=FileSystemLoader(tmpl_dir),
    block_start_string='$%',
    block_end_string='%$',
    variable_start_string='${',
    variable_end_string='}$',
    comment_start_string='$#',
    comment_end_string='#$'
    )
tmpl_file = os.path.basename(args.template)
tmpl = environment.get_template(tmpl_file)

with open(args.yaml, "r") as cv_file:
    cv_data = yaml.safe_load(cv_file)
    doc = tmpl.render(cv_data)
    with open(args.output, mode='w', encoding='utf-8') as cv:
        cv.write(doc)
